name: uptime
description: Nakime's mini cli tool.
version: 0.0.1+5
repository: https://github.com/omegaui/uptime

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.2
  excel: ^4.0.6
  intl: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
